import { ArrowUpRight, ArrowRight, ShoppingBag, Check, Code2, MousePointer2, MoveUpRight } from 'lucide-react';
const contact='mailto:hello@letsbuilda.store?subject=Let%E2%80%99s%20build%20my%20store';
function Brand(){return <a className="brand" href="#top" aria-label="Let's build a store home"><span className="brand-icon"><ShoppingBag size={23} strokeWidth={2.2}/></span><span>let’s build<span className="brand-last">a.store</span></span></a>}
export default function Home(){return <main id="top"><a className="skip" href="#main">Skip to content</a>
<header className="header wrap"><Brand/><nav aria-label="Main navigation"><a href="#approach">The approach</a><a href="#included">What you get</a></nav><a className="button small" href="#start">Let’s talk <ArrowUpRight size={17}/></a></header>
<section className="hero wrap" id="main"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> BIG IDEAS. REAL STORES.</div><h1>Let’s build<br/>a <span className="store-word">store<span className="period">.</span><svg viewBox="0 0 400 20" aria-hidden="true"><path d="M5 12 Q180 -2 393 10"/></svg></span></h1><p className="intro">You bring the ambition.<br/>We build the store around it.</p><a className="button primary" href="#start">Build something great <ArrowUpRight size={20}/></a><div className="hero-note">From first idea to the first “order confirmed.”</div></div>
<div className="hero-stage"><div className="stage-label"><span>YOUR NEXT CHAPTER</span><span>↗</span></div><div className="store-window" aria-label="Illustrative storefront concept"><div className="window-bar"><div className="window-dots"><i/><i/><i/></div><span>your-brand.store</span><span className="window-lock">↗</span></div><div className="mock-nav"><b>FORM<span>®</span></b><span>Objects for everyday.</span><ShoppingBag size={18}/></div><div className="product-scene"><img className="product-photo" src="/cobalt-speaker.png" alt="Cobalt blue speaker and an orange acrylic cube" width="1448" height="1086"/><div className="product-heading"><span>TURN IT UP.</span><span>Everyday sound.<br/>Extraordinary feeling.</span></div></div><div className="mock-bottom"><div><span className="micro">THE EVERYDAY COLLECTION</span><strong>Good things. Better online.</strong></div><span className="mock-arrow"><ArrowRight size={20}/></span></div></div><div className="floating-tag"><span className="check-icon"><Check size={18}/></span>Made for your next chapter.</div><div className="cursor" aria-hidden="true"><MousePointer2 fill="#202020" size={30}/><span>Your next store</span></div><span className="concept-label">STOREFRONT CONCEPT / 01</span></div></section>
<div className="principles"><div className="wrap principle-row"><span>Built around your business</span><span className="asterisk">✳</span><span>Designed for your customers</span><span className="asterisk">✳</span><span>Ready for what’s next</span></div></div>
<section className="approach wrap section" id="approach"><div><div className="eyebrow">01 / A BETTER START</div><h2>Your store.<br/>Not just<br/><span className="soft">another template.</span></h2></div><div className="approach-right"><p className="lead">A great store brings your brand, your products, and your customers together.</p><p>We turn what makes your business different into a store that feels unmistakably yours. From the first product page to checkout, we bring design and development together around the way your customers shop.</p><div className="approach-note"><span className="asterisk">✳</span><span>Thoughtful design.<br/>Solid development. One clear direction.</span></div></div></section>
<section className="included wrap" id="included"><div className="section-top"><div className="eyebrow">02 / FROM IDEA TO OPEN FOR BUSINESS</div><h2>All the right pieces.</h2></div><div className="cards">{[{n:'01',icon:<MousePointer2 size={25}/>,title:'A store that feels like you.',desc:'A distinctive storefront, thoughtful product pages, and a mobile experience that feels natural.',tags:'DESIGN / USER EXPERIENCE'},{n:'02',icon:<Code2 size={27}/>,title:'Built to work beautifully.',desc:'The right platform, clean development, and the connections your business needs behind the scenes.',tags:'DEVELOPMENT / INTEGRATIONS'},{n:'03',icon:<MoveUpRight size={28}/>,title:'A confident next step.',desc:'A considered launch, a practical handover, and a clear plan for where your store goes next.',tags:'LAUNCH / NEXT STEPS'}].map(c=><article className="service-card" key={c.n}><div className="card-top">{c.icon}<span>{c.n}</span></div><h3>{c.title}</h3><p>{c.desc}</p><div className="card-tags">{c.tags}</div></article>)}</div></section>
<section className="start wrap" id="start"><div className="start-panel"><div className="eyebrow">THAT IDEA YOU’VE BEEN THINKING ABOUT?</div><div className="start-row"><h2>Let’s make<br/>it <span>happen.</span></h2><div className="start-copy"><p>Tell us what you want to sell.<br/>Let’s figure out what comes next.</p><a className="button dark" href={contact}>Let’s talk about your store <ArrowUpRight size={20}/></a><span className="contact-note">hello@letsbuilda.store</span></div></div></div></section>
<footer className="footer wrap"><Brand/><span>Good things start with “let’s.”</span><a href="#top">Back to top ↑</a></footer></main>}
